### ISSUE TITLE
Forget password -Wrong error message for adding invalid email ID

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#125]
**Describe the bug**
I have the correct email id is viyeta.h.soni@gmail.com but in forgot API, I give my email id as viyeta@example.com. Then it gives 500 server error instead of giving me error for an invalid id.

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Post/Forgot'
3. Enter an invalid email id and click send
4. See error status "500 internal server error"

**Expected behavior**
It should give relevant error related to invalid ID.

**Screenshots**

![Forget_error](https://user-images.githubusercontent.com/82687478/164952470-a66aab45-3029-44de-bfe9-4487d4109355.PNG)

**Comment by felkourdi** [comment]
Fixed
