### ISSUE TITLE
Put/Products/custom wrong status up on send

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#126]
**Describe the bug**

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Put/Products/custom'
3. Enter the barcode which already exists
4. See the status code 

**Expected behavior**
It should give 409 Barcode already exists 

**Screenshots**
![409_for_exsisting_barcode](https://user-images.githubusercontent.com/82687478/164953312-cb2272eb-ba30-4728-bfc3-8f62f4deb81c.PNG)

**Comment by supersid** [comment]
@Viyeta This is also expected behavior and if the product exists for that user it will return the product details with 200. @jjzcru can confirm this.
