### ISSUE TITLE
Wrong missing id error

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#127]
**Describe the bug**
In the case of missing id or fields, it gives 400 bad requests error instead of 422 missing or invalid errors

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Post/Products/{productID}'
3. Remove the fields 
4. See the error

**Expected behavior**
422 missing or invalid errors

**Screenshots**
![missing_product_id](https://user-images.githubusercontent.com/82687478/164954628-b5914345-f5e7-418e-a7a7-adb6ff761c63.PNG)

**Comment by felkourdi** [comment]
There are many cases in this ticket:
1- If no product ID it should give 404 "Not found" as the format should be Post/Products/{productID}, also it is mentioned in spec product can be not found. 
2- I think postman by default will give you 400 bad requests as I can see a red line (syntax error adding ',' without typing a value) 
3- When I type the correct syntax for body and remove the cost for example it gives 422
