### ISSUE TITLE
Put/Product/{productID} category id "Type" is missing

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#128]
**Describe the bug**
Put/Product/{productID} category id "Type" is missing

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Put/Product/{productID}'
3. Click on Send
4. In response even though status on ok but there is missing "Type" under category ID

**Expected behavior**
include Type

**Comment by supersid** [comment]
![image](https://user-images.githubusercontent.com/31355080/164982020-9d7a3e21-8517-4603-98b9-185d0c202fec.png)
Works for staging
