### ISSUE TITLE
Get/Product/{productID} "Type" missing inside category ID

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#129]
**Describe the bug**
"Type" missing inside category ID

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Get/Product/{productID} '
3. Click on send
4. Check the response

**Expected behavior**
"Type" should be added inside category ID

**Screenshots**
![Get_Product_Caterory_Type_Missing](https://user-images.githubusercontent.com/82687478/164954886-6d79a861-5c36-4fd8-a9f9-ed8a576905f1.PNG)

**Comment by felkourdi** [comment]
@Viyeta re-check fixed by @supersid
