### ISSUE TITLE
Get/Product/{productID} getting 422 error code which is not mentioned in specs

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#130]
**Describe the bug**
Get/Product/{productID} getting 422 error code which is not mentioned in specs

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Get/Product/{productID}'
3. Enter non existing product ID
4. Click on send
5. See error

**Expected behavior**
It should give 404 product not found 

**Screenshots**

![Get_Product_422_doesnt_exist](https://user-images.githubusercontent.com/82687478/164955003-faf3db02-0978-4ef4-8b9f-c1bb3c26ab08.PNG)

**Comment by supersid** [comment]
@Viyeta This functionality works as expected. The product id that you have provided is not a valid UUID (in terms of syntax) as a result a 422 is returned.
