### ISSUE TITLE
[staging] unable to view products in laptop which are visible on mobile device

### ISSUE THREAD

**Issue by kavishsanghvi** [GoodEnoughApp/GoodEnoughApp#136]
**Describe the bug**
The mobile device displayed all the products that the user had entered, the same login for the same user on the laptop didn't display any product. 

**To Reproduce**
1. Login using the credentials mentioned on the laptop and mobile device
2. See error

**Expected behavior**
Regardless of the device, all the products should be displayed for the same user with exact same login credentials

**Credentials**
Add the credentials where the error happened, this is to replicate **exactly** the behavior
Username: kavish2512@gmail.com
Password: example123
Authentication Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhM2FjMzg0MC0yZTliLTRhYmQtOTdiYy00MTZlYTkzM2MzMDkiLCJlbWFpbCI6ImthdmlzaDI1MTJAZ21haWwuY29tIiwiZXhwaXJlZEF0IjoiMjAyMi0wNi0yNlQwMjozMzoxMi4wMTBaIiwiaWF0IjoxNjUxMDI2NzkyLCJleHAiOjE2NTYyMTA3OTJ9.089-lJ6ZxDzJU-si-fs0sfGD8K9Ebau41ohxammsVrw

**Screenshots**
Laptop
<img width="1440" alt="Screen Shot 2022-04-26 at 9 42 59 PM" src="https://user-images.githubusercontent.com/25219677/165427055-8df40598-97b7-4f05-b791-6ff543b3e263.png">

Mobile
![IMG_1585](https://user-images.githubusercontent.com/25219677/165426970-fee7efe8-dc91-4bc5-8e91-53f17061b3ff.PNG)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: firefox

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.4.1
 - Browser: safari and mobile app

**Comment by jjzcru** [comment]
This is not an error, make sure to clear the cache to make sure you have the latest version
