### ISSUE TITLE
After Product added to shopping list "Days" or "Date" Still displayed on Home Screen

### ISSUE THREAD

**Issue by Viyeta** [GoodEnoughApp/GoodEnoughApp#137]
**Describe the bug**
After Product added to shopping list "Days" or "Date" Still displayed on Home Screen

**To Reproduce**
1. Go to 'https://good-enough-app-develop.vercel.app/'
2. Click on 'add to shopping list'
3. See error "even though product is successfully moved to shopping list the Date / Day label stays on the home screen"

**Expected behavior**
In case of single product for that specific day then the label of Date/ Day should be removed.

**Credentials**
viyeta.h.soni@gmail.com

Username: Cherry
Password: Cherry123

**Item details**
Any product

**Screenshots**
![Product_in_list_LI](https://user-images.githubusercontent.com/82687478/165611037-83b06585-b73e-4230-b62f-04aef3030818.jpg)
![After_adding_to_Shopping_Cart_LI](https://user-images.githubusercontent.com/82687478/165611236-d4a996bf-f398-4b77-9e73-9510912511d8.jpg)

**Smartphone (please complete the following information):**
 - Device: [iPhone12]
 - OS: [ iOS8.1]
 - Browser [safari]

**Comment by jjzcru** [comment]
Already fix
